"""Initial migration with all indexes

Revision ID: 3b3cbdcaf708
Revises: 
Create Date: 2025-12-11 15:09:40.649872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3cbdcaf708'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_check_in', table_name='bookings')
    op.drop_index('idx_bookings_guest', table_name='bookings')
    op.drop_index('idx_bookings_room', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.create_index(op.f('ix_bookings_check_in_date'), 'bookings', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.drop_constraint('bookings_room_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_guest_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'guests', ['guest_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.drop_constraint('guests_email_key', 'guests', type_='unique')
    op.drop_constraint('guests_passport_number_key', 'guests', type_='unique')
    op.drop_index('idx_guests_email', table_name='guests')
    op.drop_index('idx_guests_passport', table_name='guests')
    op.drop_index('idx_guests_phone', table_name='guests')
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=True)
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_passport_number'), 'guests', ['passport_number'], unique=True)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.drop_index('idx_payments_booking', table_name='payments')
    op.drop_index('idx_payments_date', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_transaction', table_name='payments')
    op.drop_constraint('payments_transaction_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.drop_constraint('payments_booking_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'])
    op.create_index(op.f('ix_room_types_id'), 'room_types', ['id'], unique=False)
    op.drop_index('idx_rooms_floor', table_name='rooms')
    op.drop_index('idx_rooms_room_type', table_name='rooms')
    op.drop_index('idx_rooms_status', table_name='rooms')
    op.create_index(op.f('ix_rooms_floor'), 'rooms', ['floor'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    op.drop_constraint('rooms_room_type_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_types', ['room_type_id'], ['id'])
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_room_type_id_fkey', 'rooms', 'room_types', ['room_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_floor'), table_name='rooms')
    op.create_index('idx_rooms_status', 'rooms', ['status'], unique=False)
    op.create_index('idx_rooms_room_type', 'rooms', ['room_type_id'], unique=False)
    op.create_index('idx_rooms_floor', 'rooms', ['floor'], unique=False)
    op.drop_index(op.f('ix_room_types_id'), table_name='room_types')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_booking_id_fkey', 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.create_unique_constraint('payments_transaction_id_key', 'payments', ['transaction_id'])
    op.create_index('idx_payments_transaction', 'payments', ['transaction_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['payment_status'], unique=False)
    op.create_index('idx_payments_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_payments_booking', 'payments', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_passport_number'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.create_index('idx_guests_phone', 'guests', ['phone'], unique=False)
    op.create_index('idx_guests_passport', 'guests', ['passport_number'], unique=False)
    op.create_index('idx_guests_email', 'guests', ['email'], unique=False)
    op.create_unique_constraint('guests_passport_number_key', 'guests', ['passport_number'])
    op.create_unique_constraint('guests_email_key', 'guests', ['email'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_guest_id_fkey', 'bookings', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_room_id_fkey', 'bookings', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in_date'), table_name='bookings')
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_room', 'bookings', ['room_id'], unique=False)
    op.create_index('idx_bookings_guest', 'bookings', ['guest_id'], unique=False)
    op.create_index('idx_bookings_check_in', 'bookings', ['check_in_date'], unique=False)
    # ### end Alembic commands ###
